/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report process liveness
         * @description Touches no dependencies. A database blip should not convince an
         *     orchestrator to restart an otherwise healthy process; it should only
         *     stop routing traffic to it.
         */
        get: operations["checkLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether this instance can serve traffic */
        get: operations["checkReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the running build
         * @description The revision is stamped in by the Go toolchain, so a running instance
         *     can be traced back to a commit without a build flag.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch this document
         * @description Public, because a contract is not a secret: a client generating itself
         *     against the API should not need a credential to learn its shape.
         */
        get: operations["getOpenAPIDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List your projects */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /**
         * Delete a project and everything under it
         * @description Services, environments and deployments are removed with the project;
         *     the database cascades rather than leaving orphaned rows behind.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectID}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a project's services */
        get: operations["listServices"];
        put?: never;
        /** Add a deployable unit to a project */
        post: operations["createService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectID}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a project's environments */
        get: operations["listEnvironments"];
        put?: never;
        /**
         * Create a preview or production environment
         * @description The subdomain is derived from the environment name and the project
         *     slug, so it cannot be chosen by the caller and cannot collide with an
         *     environment of another project.
         */
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectID}/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deployment history for a project
         * @description Newest first, across every service and environment.
         */
        get: operations["listDeployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a deployment
         * @description Returns as soon as the deployment is queued; a worker picks it up and
         *     moves it through building, deploying and live. Follow the build with
         *     the logs endpoint and the status with the fetch endpoint.
         */
        post: operations["createDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deploymentID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a deployment's status */
        get: operations["getDeployment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deploymentID}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read build and release output
         * @description Logs are followed by polling with a cursor rather than streamed. The
         *     client asks for everything after the last sequence number it has seen,
         *     so a follower that loses its connection reconnects and misses nothing,
         *     where a broken stream would have to be replayed from the start.
         */
        get: operations["getDeploymentLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List this account's keys
         * @description Never the secrets; only the prefix that identifies each one.
         */
        get: operations["listAPIKeys"];
        put?: never;
        /**
         * Mint an API key
         * @description The only response that ever carries the plaintext token. Keys are
         *     stored as SHA-256 hashes, so a lost token cannot be recovered — only
         *     replaced.
         */
        post: operations["createAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{keyID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a key
         * @description Revoking is not deleting: the row stays so an audit of what a key did
         *     still has a name to point at.
         */
        delete: operations["revokeAPIKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Liveness: {
            /** @constant */
            status: "ok";
        };
        Readiness: {
            status: string;
            database: string;
        };
        Version: {
            service: string;
            /** @description The VCS revision this binary was built from. */
            version: string;
        };
        /**
         * @description Previews are unbounded; a project may have at most one production
         *     environment, which a partial unique index enforces.
         * @enum {string}
         */
        EnvironmentKind: "preview" | "production";
        /**
         * @description The deployment lifecycle. `live`, `failed` and `superseded` are
         *     terminal: a deployment in one of them will not change again on its own,
         *     which is what tells a client to stop polling.
         * @enum {string}
         */
        DeploymentStatus: "queued" | "building" | "deploying" | "live" | "failed" | "superseded";
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            account_id: string;
            /** @description A DNS label, because it becomes part of every environment hostname. */
            slug: string;
            name: string;
            /** Format: uri */
            repo_url: string;
            default_branch: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Service: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            name: string;
            /** @description Where in the repository this service is built from. */
            source_path: string;
            /** @description The port the workload listens on inside its container. */
            port: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Environment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            kind: components["schemas"]["EnvironmentKind"];
            name: string;
            /** @description The hostname label this environment answers on. */
            subdomain: string;
            /**
             * Format: uri
             * @description The environment's public address, which survives redeployment.
             *     Derived from the subdomain and the platform's domain when the
             *     environment is rendered rather than stored, because that domain is
             *     configuration: a column would keep serving the old address after
             *     the configuration changed.
             */
            url: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Deployment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            service_id: string;
            /** Format: uuid */
            environment_id: string;
            /**
             * @description A full 40-character object ID. Short SHAs are rejected: a
             *     deployment names one commit forever, and a short SHA can become
             *     ambiguous as the repository grows.
             */
            commit_sha: string;
            status: components["schemas"]["DeploymentStatus"];
            /** @description The image built for this deployment. Absent until the build succeeds. */
            image_ref?: string;
            /**
             * Format: uri
             * @description The environment's public address, repeated here so a caller
             *     watching one deployment does not have to fetch the environment to
             *     learn where it landed. Absent until the deployment is live.
             */
            url?: string;
            /** @description Why the deployment failed. Absent unless it did. */
            error_message?: string;
            /** Format: date-time */
            queued_at: string;
            /**
             * Format: date-time
             * @description When a worker claimed the deployment.
             */
            started_at?: string;
            /**
             * Format: date-time
             * @description When the deployment reached a terminal status.
             */
            completed_at?: string;
        };
        DeploymentLog: {
            /** @description Monotonic within one deployment. The cursor a follower resumes from. */
            seq: number;
            /** @description Which output this line came from, such as `stdout` or `stderr`. */
            stream: string;
            message: string;
            /** Format: date-time */
            logged_at: string;
        };
        APIKey: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            account_id: string;
            name: string;
            /**
             * @description The leading characters of the token, enough to recognise a key in a
             *     list without being enough to use it.
             */
            token_prefix: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Absent until the key authenticates a request.
             */
            last_used_at?: string;
            /**
             * Format: date-time
             * @description Absent while the key still works.
             */
            revoked_at?: string;
        };
        ProjectList: {
            projects: components["schemas"]["Project"][];
        };
        ServiceList: {
            services: components["schemas"]["Service"][];
        };
        EnvironmentList: {
            environments: components["schemas"]["Environment"][];
        };
        DeploymentList: {
            deployments: components["schemas"]["Deployment"][];
        };
        APIKeyList: {
            api_keys: components["schemas"]["APIKey"][];
        };
        CreatedAPIKey: {
            api_key: components["schemas"]["APIKey"];
            /** @description The plaintext credential. Returned once and never again. */
            token: string;
            warning: string;
        };
        LogPage: {
            logs: components["schemas"]["DeploymentLog"][];
            /**
             * @description Where to resume. Echoed back as `after` on the next request, so a
             *     follower never has to reason about sequence numbers itself.
             */
            next_after: number;
        };
        CreateProjectInput: {
            slug: string;
            name: string;
            /**
             * Format: uri
             * @description An http or https clone URL. SSH remotes are rejected because the
             *     builder authenticates with a token rather than a deploy key, so an
             *     `ssh://` URL would fail later at clone time with a far less obvious
             *     error.
             */
            repo_url: string;
            /** @default main */
            default_branch?: string;
        };
        CreateServiceInput: {
            name: string;
            /**
             * @description Relative to the repository root. An absolute path, or one
             *     containing `..`, is refused rather than sanitised.
             * @default .
             */
            source_path?: string;
            /** @default 8080 */
            port?: number;
        };
        CreateEnvironmentInput: {
            kind: components["schemas"]["EnvironmentKind"];
            name: string;
        };
        CreateDeploymentInput: {
            /** Format: uuid */
            service_id: string;
            /**
             * Format: uuid
             * @description Must belong to the same project as the service.
             */
            environment_id: string;
            commit_sha: string;
        };
        CreateAPIKeyInput: {
            /** @description How you will recognise this key in a list. */
            name: string;
        };
        FieldError: {
            field: string;
            message: string;
        };
        Error: {
            error: {
                /** @description A stable identifier a client can branch on. */
                code: string;
                /** @description Human-readable, and not something to parse. */
                message: string;
                /**
                 * @description Echoed from the request, so a user reporting a failure can be
                 *     traced straight to its log line.
                 */
                request_id?: string;
            };
        };
        ValidationError: {
            error: {
                /** @constant */
                code: "validation_failed";
                message: string;
                request_id?: string;
                fields: components["schemas"]["FieldError"][];
            };
        };
    };
    responses: {
        /** @description The bearer token is missing, unknown or revoked. */
        Unauthenticated: {
            headers: {
                /** @description How to authenticate, as RFC 7235 requires of a 401. */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No such resource, or it belongs to another account. The two are
         *     reported identically so a caller cannot confirm that an ID exists.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A resource with those details already exists. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description One or more fields are invalid. Every rejected field is listed at once,
         *     so a caller correcting a form never has to resubmit to discover the
         *     next mistake.
         */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationError"];
            };
        };
    };
    parameters: {
        ProjectID: string;
        DeploymentID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    checkLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    checkReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The database is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description The database is not reachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The build identification of this instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    getOpenAPIDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The specification embedded in this binary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every project owned by the authenticated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectInput"];
            };
        };
        responses: {
            /** @description The created project. */
            201: {
                headers: {
                    /** @description Where the new project can be fetched. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project no longer exists. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listServices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every service in the project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    createService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceInput"];
            };
        };
        responses: {
            /** @description The created service. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every environment in the project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEnvironmentInput"];
            };
        };
        responses: {
            /** @description The created environment. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /**
             * @description The name is taken, or the project already has a production
             *     environment. A project may have at most one.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    listDeployments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project's deployments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    createDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeploymentInput"];
            };
        };
        responses: {
            /** @description The queued deployment. */
            201: {
                headers: {
                    /** @description Where the deployment's status can be fetched. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deployment"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            /**
             * @description The service and environment must both exist, belong to the
             *     authenticated account, and share a project. Anything else is
             *     reported as not found rather than as a more specific error, so a
             *     caller cannot use it to discover which IDs exist.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deploymentID: components["parameters"]["DeploymentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deployment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deployment"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    getDeploymentLogs: {
        parameters: {
            query?: {
                /**
                 * @description Return only lines with a sequence number greater than this. Pass
                 *     back the `next_after` of the previous page.
                 */
                after?: number;
            };
            header?: never;
            path: {
                deploymentID: components["parameters"]["DeploymentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of output and the cursor to resume from. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogPage"];
                };
            };
            /** @description The `after` parameter is not a non-negative integer. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listAPIKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every key, revoked ones included. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAPIKeyInput"];
            };
        };
        responses: {
            /** @description The created key and its one-time token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedAPIKey"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    revokeAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The key no longer authenticates. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            /** @description No such key, or it was already revoked. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
